plugins {
    id 'com.android.library'
    id 'kotlin-android'
}
apply plugin: 'com.diffplug.spotless'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
	namespace = "com.tyron.completion.xml"
	
	spotless {
		java {
			target "**/*.java"
			googleJavaFormat()
			}
		}
		
    defaultConfig {
        minSdk rootProject.ext.minSdkVersion 
        targetSdk rootProject.ext.targetSdkVersion 

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17 
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {

    compileOnly ('com.android.tools.build:aapt2-proto'){
       exclude group: 'com.google.guava', module: 'guava'
    }
    implementation ('com.google.protobuf:protobuf-java:3.21.5'){
       exclude group: 'com.google.guava', module: 'guava'
    }
    implementation project(path: ':event-manager') 
    
    implementation project(path: ':actions-api')
    implementation project(path: ':editor-api')
    implementation project(':fileeditor-api')

    implementation ('androidx.appcompat:appcompat:1.7.1'){
       exclude group: 'com.google.guava', module: 'guava'
    }
    implementation ('com.google.android.material:material:1.13.0'){
       exclude group: 'com.google.guava', module: 'guava'
    }

    // bytecode analysis
    api ('org.apache.bcel:bcel:6.5.0'){
       exclude group: 'com.google.guava', module: 'guava'
    }
    
    api ('org.jsoup:jsoup:1.18.1'){
       exclude group: 'com.google.guava', module: 'guava'
    }
    
    // v2 dependencies
    implementation ('it.unimi.dsi:fastutil:8.5.8'){
       exclude group: 'com.google.guava', module: 'guava'
    }
    implementation ('net.sf.kxml:kxml2:2.3.0'){
       exclude group: 'com.google.guava', module: 'guava'
    }

    implementation project(path: ':language-api')
    implementation project(path: ':completion-api')
    implementation project(path: ':common')
    implementation project(path: ':java-completion')
    compileOnly project(path: ':javac')
    implementation project(':kotlinc')

    implementation project(path: ':project')
    implementation project(path: ':manifmerger')
    implementation project(path: ':xml-repository')
    implementation project(path: ':android-common-resources')
    
    implementation("com.google.code.findbugs:jsr305:3.0.2")
}