plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

apply plugin: 'com.diffplug.spotless'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
	namespace = "com.tyron.editor"
	
    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17 
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:24.1.0'

    implementation project(path: ':logging')
    implementation project(path: ':project')
    implementation project(path: ':language-api')
    implementation project(path: ':common')
    
    implementation("org.checkerframework:checker-qual:3.50.0")
    
    implementation 'it.unimi.dsi:fastutil:8.5.8'
    
}

spotless {
		java {
			target "**/*.java"
			googleJavaFormat()
			}
}