plugins {
    id 'com.android.library'
}
apply plugin: 'kotlin-android'
apply plugin: 'com.diffplug.spotless'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
	namespace = "com.tyron.common"
	
    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17 
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}
dependencies {
 
    api 'androidx.annotation:annotation:1.8.2'
    // api 'com.google.guava:guava:33.3.0-jre'
	api 'com.google.guava:guava:33.4.8-jre'
    api 'com.google.code.gson:gson:2.11.0'
    api 'commons-io:commons-io:2.16.1'
    api 'net.lingala.zip4j:zip4j:2.11.5'
    compileOnly project(path: ':android-stubs')
	implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.0.20'
}

spotless {
		java {
			target "**/*.java"
			googleJavaFormat()
			}
}