plugins {
    id 'com.android.library'
}
 
apply plugin: 'com.diffplug.spotless'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
	namespace = "com.tyron.fileeditor"
	
    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17 
        targetCompatibility JavaVersion.VERSION_17
    }
     
}

dependencies {

    implementation project(path: ':common')
    compileOnly project(path: ':android-stubs')
    implementation project(':editor-api')
    implementation 'androidx.annotation:annotation:1.8.2'
    
    implementation 'org.slf4j:slf4j-api:1.7.36' 
    implementation 'androidx.annotation:annotation:1.3.0'
    implementation 'org.apache.commons:commons-vfs2:2.9.0'
}

spotless {
		java {
			target "**/*.java"
			googleJavaFormat()
			}
}