name: Android CI Release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4              

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run:  ./gradlew :app:spotlessApply && ./gradlew clean && ./gradlew assembleRelease

      - name: Upload debug apk
        uses: actions/upload-artifact@v4
        if: ${{ !github.head_ref }}
        with:
          name: apk-release
          path: app/build/outputs/apk/release/app-release.apk
